# gauss_law.py

# can use Gauss' Law of electric flux to find the flux through a given
# Gaussian surface, the charge enclosed by the surface, or the strength of the
# electric field

import sympy

epsilon_0 = 8.85e-12  # vacuum permittivity constant
pi = sympy.pi


def charge_or_field():
    c_or_f = input("\nWhat is given?\n1. Charge Enclosed (Q)\n"
                   "2. Electric Field (E) and Radius\n")
    if c_or_f == "1":
        flux_from_charge()


def flux_from_charge():
    Q = sympy.sympify(input("\nWhat is the charge enclosed?\n"))
    phi = Q / epsilon_0
    print(f"\nThe electric flux generated by a charge of {Q} C is {phi} Vm.\n")


def flux_from_field(E, A):
    return E * A


def find_field(Q, A):
    return Q/(epsilon_0 * A)


def find_charge(E, A):
    return E * A * epsilon_0


while True:
    equation = input("\nWhat would you like to use Gauss' Law to find?\n"
                     "1. Electric Flux (\u03A6)\n2. Electric Field (E)\n"
                     "3. Charge Enclosed (Q)\n")

    if equation == "1":
        charge_or_field()

    print("Press 'x' to exit, or press enter to try a new equation.")
    if input() == "x":
        break
